name: examify_app
description: Modern teacher UI for Examify (Demo).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  google_sign_in: ^6.3.0
  google_fonts: ^6.3.2
  flutter_facebook_auth: ^7.1.2
  http: ^1.5.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  advanced_salomon_bottom_bar: ^3.3.4
  excel: ^4.0.6
  file_picker: 10.3.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^12.0.1
  device_info_plus: ^9.0.0
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.3
  cloud_firestore: ^4.11.0
  flutter_local_notifications: ^13.0.0

dependency_overrides:
  permission_handler_android: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
